/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class modle_test_com_commlibary_Speex_jni */

#ifndef _Included_modle_test_com_commlibary_Speex_jni
#define _Included_modle_test_com_commlibary_Speex_jni
#ifdef __cplusplus
extern "C" {
#endif
#undef modle_test_com_commlibary_Speex_jni_DEFAULT_COMPRESSION
#define modle_test_com_commlibary_Speex_jni_DEFAULT_COMPRESSION 8L
/*
 * Class:     modle_test_com_commlibary_Speex_jni
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_modle_test_com_commlibary_Speex_1jni_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     modle_test_com_commlibary_Speex_jni
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_modle_test_com_commlibary_Speex_1jni_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     modle_test_com_commlibary_Speex_jni
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_modle_test_com_commlibary_Speex_1jni_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     modle_test_com_commlibary_Speex_jni
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_modle_test_com_commlibary_Speex_1jni_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     modle_test_com_commlibary_Speex_jni
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_modle_test_com_commlibary_Speex_1jni_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
